// Generated from TransferSpace_Backend/supabase_schools_cds_import.csv.
// Source notes come from TransferSpace_Backend/supabase_schools_cds_notes.csv.
window.TRANSFERSPACE_SCHOOL_DATA = [
  {
    "id": "204796",
    "name": "Ohio State University-Main Campus",
    "state": "OH",
    "location": "Columbus",
    "type": "Public",
    "acceptance_rate_transfer": "0.863",
    "avg_gpa_transfer": "",
    "undergrad_population": "45638",
    "tuition_in_state": "13244",
    "tuition_out_of_state": "40022",
    "app_fee": "60",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "30",
    "popular_majors": "[\"Business\", \"Engineering\", \"Health & Medicine\", \"Biology\", \"Social Sciences\"]",
    "transfer_info_link": "https://undergrad.osu.edu/apply/transfer",
    "apply_link": "https://undergrad.osu.edu/apply/transfer",
    "school_url": "https://www.osu.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "2.0",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C",
    "fall-closing-date": "5/15",
    "spring-closing-date": "11/1",
    "fall-notification-date": "",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2023-24 Ohio State University.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "186380",
    "name": "Rutgers University-New Brunswick",
    "state": "NJ",
    "location": "New Brunswick",
    "type": "Public",
    "acceptance_rate_transfer": "0.5757",
    "avg_gpa_transfer": "",
    "undergrad_population": "37751",
    "tuition_in_state": "17929",
    "tuition_out_of_state": "37441",
    "app_fee": "70",
    "is_need_blind": "false",
    "max_credits_accepted": "60",
    "residency_credits_required": "",
    "popular_majors": "[\"Business\", \"Computer Science\", \"Engineering\", \"Health & Medicine\", \"Biology\"]",
    "transfer_info_link": "https://admissions.rutgers.edu/transfer-students",
    "apply_link": "https://admissions.rutgers.edu/transfer-students",
    "school_url": "https://newbrunswick.rutgers.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "2/1",
    "spring-closing-date": "10/1",
    "fall-notification-date": "4/15",
    "spring-notification-date": "12/1",
    "_source_file": "Common_Data_Sets_2025/2023-24 Rutgers University-New Brunswick.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "179867",
    "name": "Washington University in St Louis",
    "state": "MO",
    "location": "St. Louis",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.1401",
    "avg_gpa_transfer": "",
    "undergrad_population": "7857",
    "tuition_in_state": "65790",
    "tuition_out_of_state": "65790",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "60",
    "residency_credits_required": "",
    "popular_majors": "[\"Engineering\", \"Biology\", \"Social Sciences\", \"Computer Science\", \"Business\"]",
    "transfer_info_link": "https://admissions.wustl.edu/how-to-apply/transfer-applicants/",
    "apply_link": "https://admissions.wustl.edu/how-to-apply/transfer-applicants/",
    "school_url": "https://washu.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "",
    "min_credits_required": "12",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C",
    "fall-closing-date": "March 2",
    "spring-closing-date": "October 15",
    "fall-notification-date": "May 15",
    "spring-notification-date": "November 14",
    "_source_file": "Common_Data_Sets_2025/2024-2025-WashU-CDS.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "164924",
    "name": "Boston College",
    "state": "MA",
    "location": "Chestnut Hill",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.277",
    "avg_gpa_transfer": "",
    "undergrad_population": "10085",
    "tuition_in_state": "70702",
    "tuition_out_of_state": "70702",
    "app_fee": "80",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Business\", \"Social Sciences\", \"Biology\", \"Psychology\", \"Computer Science\"]",
    "transfer_info_link": "https://www.bc.edu/bc-web/admission/apply/transfer.html",
    "apply_link": "https://www.bc.edu/bc-web/admission/apply/transfer.html",
    "school_url": "https://www.bc.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "March 15",
    "spring-closing-date": "November 1",
    "fall-notification-date": "May 20",
    "spring-notification-date": "December 15",
    "_source_file": "Common_Data_Sets_2025/2024-25 Boston College.pdf",
    "_source_notes": "Official Boston College transfer page deadline fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "164988",
    "name": "Boston University",
    "state": "MA",
    "location": "Boston",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.346",
    "avg_gpa_transfer": "3.78",
    "undergrad_population": "18248",
    "tuition_in_state": "68102",
    "tuition_out_of_state": "68102",
    "app_fee": "80",
    "is_need_blind": "false",
    "max_credits_accepted": "68",
    "residency_credits_required": "",
    "popular_majors": "[\"Business\", \"Social Sciences\", \"Biology\", \"Computer Science\", \"Engineering\"]",
    "transfer_info_link": "https://www.bu.edu/admissions/apply/transfer/",
    "apply_link": "https://www.bu.edu/admissions/apply/transfer/",
    "school_url": "https://www.bu.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C",
    "fall-closing-date": "3/15",
    "spring-closing-date": "11/1",
    "fall-notification-date": "Mid April",
    "spring-notification-date": "Mid November to Mid December",
    "_source_file": "Common_Data_Sets_2025/2024-25 Boston University.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "217156",
    "name": "Brown University",
    "state": "RI",
    "location": "Providence",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.072",
    "avg_gpa_transfer": "",
    "undergrad_population": "7226",
    "tuition_in_state": "71412",
    "tuition_out_of_state": "71412",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "60",
    "residency_credits_required": "60",
    "popular_majors": "[\"Social Sciences\", \"Computer Science\", \"Biology\", \"Engineering\", \"Psychology\"]",
    "transfer_info_link": "https://admission.brown.edu/transfer",
    "apply_link": "https://admission.brown.edu/transfer",
    "school_url": "https://www.brown.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "true",
    "min_gpa": "",
    "min_credits_required": "28",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "03/01",
    "spring-closing-date": "10/01",
    "fall-notification-date": "May",
    "spring-notification-date": "Early December",
    "_source_file": "Common_Data_Sets_2025/2024-25 Brown University.pdf",
    "_source_notes": "Used legacy CDS.txt minimum credits fallback.; Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "110404",
    "name": "California Institute of Technology",
    "state": "CA",
    "location": "Pasadena",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.062",
    "avg_gpa_transfer": "",
    "undergrad_population": "987",
    "tuition_in_state": "65898",
    "tuition_out_of_state": "65898",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "216",
    "popular_majors": "[\"Computer Science\", \"Engineering\", \"Biology\", \"Business\"]",
    "transfer_info_link": "https://www.admissions.caltech.edu/apply/transfer-applicants",
    "apply_link": "https://www.admissions.caltech.edu/apply/transfer-applicants",
    "school_url": "https://www.caltech.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "February 1",
    "spring-closing-date": "",
    "fall-notification-date": "Mid-April",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 California Institute of Technology.pdf",
    "_source_notes": "Could not confidently parse D2 applicants/admitted/enrolled.; Used legacy CDS.txt acceptance rate fallback.; Used legacy CDS.txt residency credits fallback.; Official Caltech transfer deadlines page fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "211440",
    "name": "Carnegie Mellon University",
    "state": "PA",
    "location": "Pittsburgh",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0557",
    "avg_gpa_transfer": "",
    "undergrad_population": "7304",
    "tuition_in_state": "66246",
    "tuition_out_of_state": "66246",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Engineering\", \"Computer Science\", \"Business\", \"Social Sciences\", \"Biology\"]",
    "transfer_info_link": "https://www.cmu.edu/admission/admission/transfer-applicants",
    "apply_link": "https://www.cmu.edu/admission/admission/transfer-applicants",
    "school_url": "https://www.cmu.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "true",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "February 15",
    "spring-closing-date": "October 15",
    "fall-notification-date": "",
    "spring-notification-date": "December 15",
    "_source_file": "Common_Data_Sets_2025/2024-25 Carnegie Mellon University.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "190150",
    "name": "Columbia University",
    "state": "NY",
    "location": "New York",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.5241",
    "avg_gpa_transfer": "",
    "undergrad_population": "8973",
    "tuition_in_state": "71845",
    "tuition_out_of_state": "71845",
    "app_fee": "80",
    "is_need_blind": "false",
    "max_credits_accepted": "60",
    "residency_credits_required": "64",
    "popular_majors": "[\"Social Sciences\", \"Computer Science\", \"Engineering\", \"Biology\", \"Psychology\"]",
    "transfer_info_link": "https://undergrad.admissions.columbia.edu/apply/transfer",
    "apply_link": "https://undergrad.admissions.columbia.edu/apply/transfer",
    "school_url": "https://www.columbia.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "true",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "January 15",
    "spring-closing-date": "September 1",
    "fall-notification-date": "May 15",
    "spring-notification-date": "November 1",
    "_source_file": "Common_Data_Sets_2025/2024-25 Columbia University.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "190415",
    "name": "Cornell University",
    "state": "NY",
    "location": "Ithaca",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0928",
    "avg_gpa_transfer": "",
    "undergrad_population": "15995",
    "tuition_in_state": "69314",
    "tuition_out_of_state": "69314",
    "app_fee": "80",
    "is_need_blind": "false",
    "max_credits_accepted": "60",
    "residency_credits_required": "60",
    "popular_majors": "[\"Computer Science\", \"Business\", \"Engineering\", \"Biology\", \"Social Sciences\"]",
    "transfer_info_link": "https://admissions.cornell.edu/apply/transfer-applicants",
    "apply_link": "https://admissions.cornell.edu/apply/transfer-applicants",
    "school_url": "https://www.cornell.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "12",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C",
    "fall-closing-date": "3/15",
    "spring-closing-date": "",
    "fall-notification-date": "6/15",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Cornell University.pdf",
    "_source_notes": "Could not confidently parse D2 applicants/admitted/enrolled.; Parsed AcroForm transfer totals. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "182670",
    "name": "Dartmouth College",
    "state": "NH",
    "location": "Hanover",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0665",
    "avg_gpa_transfer": "",
    "undergrad_population": "4541",
    "tuition_in_state": "68268",
    "tuition_out_of_state": "68268",
    "app_fee": "90",
    "is_need_blind": "false",
    "max_credits_accepted": "68",
    "residency_credits_required": "72",
    "popular_majors": "[\"Social Sciences\", \"Engineering\", \"Computer Science\", \"Biology\", \"Psychology\"]",
    "transfer_info_link": "https://admissions.dartmouth.edu/glossary-question/transfer-applicants",
    "apply_link": "https://admissions.dartmouth.edu/glossary-question/transfer-applicants",
    "school_url": "https://dartmouth.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "3/1",
    "spring-closing-date": "",
    "fall-notification-date": "5/15",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Dartmouth College.pdf",
    "_source_notes": "Used legacy CDS.txt max credits fallback.; Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "198419",
    "name": "Duke University",
    "state": "NC",
    "location": "Durham",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0403",
    "avg_gpa_transfer": "",
    "undergrad_population": "6442",
    "tuition_in_state": "68758",
    "tuition_out_of_state": "68758",
    "app_fee": "85",
    "is_need_blind": "false",
    "max_credits_accepted": "17",
    "residency_credits_required": "17",
    "popular_majors": "[\"Social Sciences\", \"Biology\", \"Computer Science\", \"Engineering\", \"Health & Medicine\"]",
    "transfer_info_link": "https://admissions.duke.edu/apply/",
    "apply_link": "https://admissions.duke.edu/apply/",
    "school_url": "https://www.duke.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "2.4",
    "min_credits_required": "",
    "accepts_fall": "false",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C",
    "fall-closing-date": "3/15",
    "spring-closing-date": "",
    "fall-notification-date": "5/15",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Duke University.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "139658",
    "name": "Emory University",
    "state": "GA",
    "location": "Atlanta",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.162",
    "avg_gpa_transfer": "",
    "undergrad_population": "7298",
    "tuition_in_state": "64280",
    "tuition_out_of_state": "64280",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Business\", \"Biology\", \"Social Sciences\", \"Health & Medicine\", \"Psychology\"]",
    "transfer_info_link": "https://apply.emory.edu/apply/transfer.html",
    "apply_link": "https://apply.emory.edu/apply/transfer.html",
    "school_url": "https://www.emory.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "3.0",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "3/15",
    "spring-closing-date": "",
    "fall-notification-date": "5/1",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Emory University.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "131496",
    "name": "Georgetown University",
    "state": "DC",
    "location": "Washington",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0593",
    "avg_gpa_transfer": "",
    "undergrad_population": "7569",
    "tuition_in_state": "68017",
    "tuition_out_of_state": "68017",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Social Sciences\", \"Business\", \"Biology\", \"Health & Medicine\", \"Psychology\"]",
    "transfer_info_link": "https://uadmissions.georgetown.edu/applying/transfer/",
    "apply_link": "https://uadmissions.georgetown.edu/applying/transfer/",
    "school_url": "https://www.georgetown.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "3.0",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "3/1",
    "spring-closing-date": "3/1",
    "fall-notification-date": "6/1",
    "spring-notification-date": "6/1",
    "_source_file": "Common_Data_Sets_2025/2024-25 Georgetown University.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "139755",
    "name": "Georgia Institute of Technology-Main Campus",
    "state": "GA",
    "location": "Atlanta",
    "type": "Public",
    "acceptance_rate_transfer": "0.2067",
    "avg_gpa_transfer": "",
    "undergrad_population": "18785",
    "tuition_in_state": "12058",
    "tuition_out_of_state": "34484",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Engineering\", \"Computer Science\", \"Business\", \"Biology\", \"Social Sciences\"]",
    "transfer_info_link": "https://admission.gatech.edu/transfer/",
    "apply_link": "https://admission.gatech.edu/transfer/",
    "school_url": "https://www.gatech.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "3.0",
    "min_credits_required": "30",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "1/20",
    "spring-closing-date": "8/1",
    "fall-notification-date": "3/3",
    "spring-notification-date": "9/16",
    "_source_file": "Common_Data_Sets_2025/2024-25 Georgia Institute of Technology.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "166027",
    "name": "Harvard University",
    "state": "MA",
    "location": "Cambridge",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0071",
    "avg_gpa_transfer": "",
    "undergrad_population": "7601",
    "tuition_in_state": "61676",
    "tuition_out_of_state": "61676",
    "app_fee": "85",
    "is_need_blind": "false",
    "max_credits_accepted": "32",
    "residency_credits_required": "32",
    "popular_majors": "[\"Social Sciences\", \"Biology\", \"Computer Science\", \"Engineering\", \"Psychology\"]",
    "transfer_info_link": "https://college.harvard.edu/admissions/apply/transfer-applicants",
    "apply_link": "https://college.harvard.edu/admissions/apply/transfer-applicants",
    "school_url": "https://www.harvard.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "16",
    "accepts_fall": "",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C",
    "fall-closing-date": "3/1",
    "spring-closing-date": "",
    "fall-notification-date": "6/15",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Harvard University.pdf",
    "_source_notes": "Used legacy CDS.txt minimum credits fallback.; Used legacy CDS.txt max credits fallback.; Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "162928",
    "name": "Johns Hopkins University",
    "state": "MD",
    "location": "Baltimore",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0527",
    "avg_gpa_transfer": "",
    "undergrad_population": "5693",
    "tuition_in_state": "65230",
    "tuition_out_of_state": "65230",
    "app_fee": "70",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Biology\", \"Engineering\", \"Computer Science\", \"Social Sciences\", \"Health & Medicine\"]",
    "transfer_info_link": "https://apply.jhu.edu/transfer-applicants/",
    "apply_link": "https://apply.jhu.edu/transfer-applicants/",
    "school_url": "https://www.jhu.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "3.0",
    "min_credits_required": "12",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "3/1",
    "spring-closing-date": "",
    "fall-notification-date": "5/13",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Johns Hopkins University.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "166683",
    "name": "Massachusetts Institute of Technology",
    "state": "MA",
    "location": "Cambridge",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0238",
    "avg_gpa_transfer": "",
    "undergrad_population": "4535",
    "tuition_in_state": "62396",
    "tuition_out_of_state": "62396",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Engineering\", \"Computer Science\", \"Biology\", \"Business\", \"Social Sciences\"]",
    "transfer_info_link": "https://mitadmissions.org/apply/transfer/",
    "apply_link": "https://mitadmissions.org/apply/transfer/",
    "school_url": "https://web.mit.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "B",
    "fall-closing-date": "May",
    "spring-closing-date": "10/15",
    "fall-notification-date": "5/4",
    "spring-notification-date": "11/15",
    "_source_file": "Common_Data_Sets_2025/2024-25 Massachusetts Institute of Technology.xlsx.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "193900",
    "name": "New York University",
    "state": "NY",
    "location": "New York",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.2209",
    "avg_gpa_transfer": "",
    "undergrad_population": "28663",
    "tuition_in_state": "62796",
    "tuition_out_of_state": "62796",
    "app_fee": "85",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Social Sciences\", \"Business\", \"Computer Science\", \"Health & Medicine\", \"Psychology\"]",
    "transfer_info_link": "https://www.nyu.edu/admissions/undergraduate-admissions/how-to-apply/transfer-applicants.html",
    "apply_link": "https://www.nyu.edu/admissions/undergraduate-admissions/how-to-apply/transfer-applicants.html",
    "school_url": "https://www.nyu.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "3/15",
    "spring-closing-date": "10/15",
    "fall-notification-date": "May",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 New York University.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "147767",
    "name": "Northwestern University",
    "state": "IL",
    "location": "Evanston",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.1197",
    "avg_gpa_transfer": "",
    "undergrad_population": "9201",
    "tuition_in_state": "68322",
    "tuition_out_of_state": "68322",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "48",
    "residency_credits_required": "23",
    "popular_majors": "[\"Engineering\", \"Social Sciences\", \"Biology\", \"Computer Science\", \"Psychology\"]",
    "transfer_info_link": "https://admissions.northwestern.edu/apply/transfer/",
    "apply_link": "https://admissions.northwestern.edu/apply/transfer/",
    "school_url": "https://www.northwestern.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "24",
    "accepts_fall": "true",
    "accepts_spring": "",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "3/15",
    "spring-closing-date": "",
    "fall-notification-date": "",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Northwestern University.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "186131",
    "name": "Princeton University",
    "state": "NJ",
    "location": "Princeton",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0191",
    "avg_gpa_transfer": "",
    "undergrad_population": "5709",
    "tuition_in_state": "62688",
    "tuition_out_of_state": "62688",
    "app_fee": "70",
    "is_need_blind": "false",
    "max_credits_accepted": "68",
    "residency_credits_required": "56",
    "popular_majors": "[\"Social Sciences\", \"Engineering\", \"Computer Science\", \"Biology\", \"Psychology\"]",
    "transfer_info_link": "https://admission.princeton.edu/apply/transfer-applicants",
    "apply_link": "https://admission.princeton.edu/apply/transfer-applicants",
    "school_url": "https://www.princeton.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "3/1",
    "spring-closing-date": "",
    "fall-notification-date": "May",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Princeton.pdf",
    "_source_notes": "Used legacy CDS.txt max credits fallback.; Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "227757",
    "name": "Rice University",
    "state": "TX",
    "location": "Houston",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0692",
    "avg_gpa_transfer": "",
    "undergrad_population": "4776",
    "tuition_in_state": "64144",
    "tuition_out_of_state": "64144",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Engineering\", \"Biology\", \"Computer Science\", \"Social Sciences\", \"Business\"]",
    "transfer_info_link": "https://admission.rice.edu/apply/transfer",
    "apply_link": "https://admission.rice.edu/apply/transfer",
    "school_url": "https://www.rice.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "3.2",
    "min_credits_required": "12",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "March 15",
    "spring-closing-date": "October 15",
    "fall-notification-date": "June",
    "spring-notification-date": "December 1",
    "_source_file": "Common_Data_Sets_2025/2024-25 Rice University.pdf",
    "_source_notes": "Official Rice transfer applicants page fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "243744",
    "name": "Stanford University",
    "state": "CA",
    "location": "Stanford",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.016",
    "avg_gpa_transfer": "",
    "undergrad_population": "7554",
    "tuition_in_state": "65910",
    "tuition_out_of_state": "65910",
    "app_fee": "90",
    "is_need_blind": "false",
    "max_credits_accepted": "90",
    "residency_credits_required": "90",
    "popular_majors": "[\"Computer Science\", \"Engineering\", \"Social Sciences\", \"Biology\", \"Psychology\"]",
    "transfer_info_link": "https://admission.stanford.edu/apply/transfer",
    "apply_link": "https://admission.stanford.edu/apply/transfer",
    "school_url": "https://www.stanford.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "0",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C-",
    "fall-closing-date": "3/15",
    "spring-closing-date": "",
    "fall-notification-date": "5/15",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Stanford University.pdf",
    "_source_notes": "Could not confidently parse D2 applicants/admitted/enrolled.; Used legacy CDS.txt acceptance rate fallback.; Used legacy CDS.txt max credits fallback.; Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "168148",
    "name": "Tufts University",
    "state": "MA",
    "location": "Medford",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.2124",
    "avg_gpa_transfer": "",
    "undergrad_population": "7061",
    "tuition_in_state": "70704",
    "tuition_out_of_state": "70704",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Social Sciences\", \"Engineering\", \"Biology\", \"Computer Science\", \"Psychology\"]",
    "transfer_info_link": "https://admissions.tufts.edu/apply/transfer-students/",
    "apply_link": "https://admissions.tufts.edu/apply/transfer-students/",
    "school_url": "https://www.tufts.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "12",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "March 17",
    "spring-closing-date": "",
    "fall-notification-date": "May",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Tufts University.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "160755",
    "name": "Tulane University of Louisiana",
    "state": "LA",
    "location": "New Orleans",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.6007",
    "avg_gpa_transfer": "",
    "undergrad_population": "7767",
    "tuition_in_state": "68678",
    "tuition_out_of_state": "68678",
    "app_fee": "0",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "60",
    "popular_majors": "[\"Business\", \"Social Sciences\", \"Biology\", \"Psychology\", \"Health & Medicine\"]",
    "transfer_info_link": "https://admission.tulane.edu/transfer-students",
    "apply_link": "https://admission.tulane.edu/transfer-students",
    "school_url": "https://tulane.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "",
    "min_credits_required": "12",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "2/1",
    "spring-closing-date": "10/15",
    "fall-notification-date": "4/15",
    "spring-notification-date": "12/1",
    "_source_file": "Common_Data_Sets_2025/2024-25 Tulane University.pdf",
    "_source_notes": "Used legacy CDS.txt minimum credits fallback.; Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "110635",
    "name": "University of California-Berkeley",
    "state": "CA",
    "location": "Berkeley",
    "type": "Public",
    "acceptance_rate_transfer": "0.2555",
    "avg_gpa_transfer": "",
    "undergrad_population": "33068",
    "tuition_in_state": "16347",
    "tuition_out_of_state": "50547",
    "app_fee": "80",
    "is_need_blind": "false",
    "max_credits_accepted": "70",
    "residency_credits_required": "60",
    "popular_majors": "[\"Computer Science\", \"Social Sciences\", \"Engineering\", \"Biology\", \"Business\"]",
    "transfer_info_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "apply_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "school_url": "https://www.berkeley.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "2.4",
    "min_credits_required": "60",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C",
    "fall-closing-date": "11/30",
    "spring-closing-date": "D908 Summer",
    "fall-notification-date": "4/30",
    "spring-notification-date": "D912 Summer",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of California, Berkeley.xlsx.pdf",
    "_source_notes": "Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "110644",
    "name": "University of California-Davis",
    "state": "CA",
    "location": "Davis",
    "type": "Public",
    "acceptance_rate_transfer": "0.5817",
    "avg_gpa_transfer": "",
    "undergrad_population": "32253",
    "tuition_in_state": "16774",
    "tuition_out_of_state": "50974",
    "app_fee": "80",
    "is_need_blind": "false",
    "max_credits_accepted": "70",
    "residency_credits_required": "35",
    "popular_majors": "[\"Biology\", \"Social Sciences\", \"Psychology\", \"Engineering\", \"Business\"]",
    "transfer_info_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "apply_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "school_url": "https://ucdavis.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "2.4",
    "min_credits_required": "60",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "11/30",
    "spring-closing-date": "",
    "fall-notification-date": "April 30",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of California, Davis.pdf",
    "_source_notes": "Used legacy CDS.txt minimum credits fallback.; Used legacy CDS.txt max credits fallback.; Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "110653",
    "name": "University of California-Irvine",
    "state": "CA",
    "location": "Irvine",
    "type": "Public",
    "acceptance_rate_transfer": "0.3993",
    "avg_gpa_transfer": "",
    "undergrad_population": "30197",
    "tuition_in_state": "15722",
    "tuition_out_of_state": "49922",
    "app_fee": "80",
    "is_need_blind": "false",
    "max_credits_accepted": "105",
    "residency_credits_required": "36",
    "popular_majors": "[\"Social Sciences\", \"Psychology\", \"Business\", \"Biology\", \"Engineering\"]",
    "transfer_info_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "apply_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "school_url": "https://www.uci.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "2.4",
    "min_credits_required": "45",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "6/1",
    "spring-closing-date": "",
    "fall-notification-date": "",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of California, Irvine.pdf",
    "_source_notes": "Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "110662",
    "name": "University of California-Los Angeles",
    "state": "CA",
    "location": "Los Angeles",
    "type": "Public",
    "acceptance_rate_transfer": "0.228",
    "avg_gpa_transfer": "",
    "undergrad_population": "33475",
    "tuition_in_state": "15203",
    "tuition_out_of_state": "49403",
    "app_fee": "80",
    "is_need_blind": "false",
    "max_credits_accepted": "70",
    "residency_credits_required": "68",
    "popular_majors": "[\"Social Sciences\", \"Biology\", \"Psychology\", \"Engineering\", \"Computer Science\"]",
    "transfer_info_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "apply_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "school_url": "https://www.ucla.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "2.8",
    "min_credits_required": "60",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "2.4",
    "lowest_letter_grade_for_credit": "D-",
    "fall-closing-date": "11/30",
    "spring-closing-date": "",
    "fall-notification-date": "4/30",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of California, Los Angeles.pdf",
    "_source_notes": "Could not confidently parse D2 applicants/admitted/enrolled.; Used legacy CDS.txt acceptance rate fallback.; Used legacy CDS.txt minimum credits fallback.; Used legacy CDS.txt max credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "110671",
    "name": "University of California-Riverside",
    "state": "CA",
    "location": "Riverside",
    "type": "Public",
    "acceptance_rate_transfer": "0.5841",
    "avg_gpa_transfer": "",
    "undergrad_population": "22593",
    "tuition_in_state": "15606",
    "tuition_out_of_state": "49806",
    "app_fee": "80",
    "is_need_blind": "false",
    "max_credits_accepted": "70",
    "residency_credits_required": "36",
    "popular_majors": "[\"Social Sciences\", \"Biology\", \"Business\", \"Psychology\", \"Engineering\"]",
    "transfer_info_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "apply_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "school_url": "https://www.ucr.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "2.4",
    "min_credits_required": "60",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "12/02",
    "spring-closing-date": "",
    "fall-notification-date": "3/31",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of California, Riverside.pdf",
    "_source_notes": "Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "110680",
    "name": "University of California-San Diego",
    "state": "CA",
    "location": "La Jolla",
    "type": "Public",
    "acceptance_rate_transfer": "0.5455",
    "avg_gpa_transfer": "",
    "undergrad_population": "34948",
    "tuition_in_state": "16758",
    "tuition_out_of_state": "50958",
    "app_fee": "80",
    "is_need_blind": "false",
    "max_credits_accepted": "106",
    "residency_credits_required": "68",
    "popular_majors": "[\"Biology\", \"Engineering\", \"Social Sciences\", \"Psychology\", \"Computer Science\"]",
    "transfer_info_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "apply_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "school_url": "https://www.ucsd.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "3.0",
    "min_credits_required": "60",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "11/30",
    "spring-closing-date": "",
    "fall-notification-date": "4/28",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of California, San Diego.pdf",
    "_source_notes": "Used legacy CDS.txt minimum credits fallback.; Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "110705",
    "name": "University of California-Santa Barbara",
    "state": "CA",
    "location": "Santa Barbara",
    "type": "Public",
    "acceptance_rate_transfer": "0.6165",
    "avg_gpa_transfer": "",
    "undergrad_population": "23113",
    "tuition_in_state": "16414",
    "tuition_out_of_state": "50614",
    "app_fee": "80",
    "is_need_blind": "false",
    "max_credits_accepted": "70",
    "residency_credits_required": "35",
    "popular_majors": "[\"Social Sciences\", \"Biology\", \"Psychology\", \"Engineering\", \"Computer Science\"]",
    "transfer_info_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "apply_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "school_url": "https://www.ucsb.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "60",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "11/30",
    "spring-closing-date": "",
    "fall-notification-date": "3/15",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of California, Santa Barbara.pdf",
    "_source_notes": "Used legacy CDS.txt minimum credits fallback.; Used legacy CDS.txt max credits fallback.; Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "110714",
    "name": "University of California-Santa Cruz",
    "state": "CA",
    "location": "Santa Cruz",
    "type": "Public",
    "acceptance_rate_transfer": "0.644",
    "avg_gpa_transfer": "",
    "undergrad_population": "17940",
    "tuition_in_state": "16005",
    "tuition_out_of_state": "50205",
    "app_fee": "80",
    "is_need_blind": "false",
    "max_credits_accepted": "70",
    "residency_credits_required": "35",
    "popular_majors": "[\"Computer Science\", \"Biology\", \"Social Sciences\", \"Psychology\", \"Business\"]",
    "transfer_info_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "apply_link": "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/",
    "school_url": "https://www.ucsc.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "true",
    "min_gpa": "",
    "min_credits_required": "60",
    "accepts_fall": "true",
    "accepts_spring": "",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "December 1",
    "spring-closing-date": "",
    "fall-notification-date": "March-May",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of California, Santa Cruz.pdf",
    "_source_notes": "Could not confidently parse D2 applicants/admitted/enrolled.; Used legacy CDS.txt acceptance rate fallback.; Used legacy CDS.txt minimum credits fallback.; Used legacy CDS.txt max credits fallback.; Used legacy CDS.txt residency credits fallback.; Official UC transfer dates page fallback; winter date is represented in app term overrides. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "144050",
    "name": "University of Chicago",
    "state": "IL",
    "location": "Chicago",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0929",
    "avg_gpa_transfer": "",
    "undergrad_population": "7569",
    "tuition_in_state": "70662",
    "tuition_out_of_state": "70662",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Social Sciences\", \"Biology\", \"Computer Science\", \"Psychology\", \"Engineering\"]",
    "transfer_info_link": "https://collegeadmissions.uchicago.edu/apply/transfer-applicants",
    "apply_link": "https://collegeadmissions.uchicago.edu/apply/transfer-applicants",
    "school_url": "https://www.uchicago.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "March 1",
    "spring-closing-date": "",
    "fall-notification-date": "",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of Chicago.pdf",
    "_source_notes": "Official UChicago admissions PDF priority transfer deadline fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "134130",
    "name": "University of Florida",
    "state": "FL",
    "location": "Gainesville",
    "type": "Public",
    "acceptance_rate_transfer": "0.4486",
    "avg_gpa_transfer": "",
    "undergrad_population": "35629",
    "tuition_in_state": "6381",
    "tuition_out_of_state": "28659",
    "app_fee": "30",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Engineering\", \"Business\", \"Biology\", \"Social Sciences\", \"Health & Medicine\"]",
    "transfer_info_link": "https://admissions.ufl.edu/apply/transfer/",
    "apply_link": "https://admissions.ufl.edu/apply/transfer/",
    "school_url": "https://www.ufl.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "2.0",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "5/1",
    "spring-closing-date": "9/15",
    "fall-notification-date": "5/1",
    "spring-notification-date": "9/15",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of Florida.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "145637",
    "name": "University of Illinois Urbana-Champaign",
    "state": "IL",
    "location": "Champaign",
    "type": "Public",
    "acceptance_rate_transfer": "0.4237",
    "avg_gpa_transfer": "",
    "undergrad_population": "36258",
    "tuition_in_state": "16004",
    "tuition_out_of_state": "35124",
    "app_fee": "50",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Engineering\", \"Business\", \"Computer Science\", \"Social Sciences\", \"Psychology\"]",
    "transfer_info_link": "https://www.admissions.illinois.edu/apply/transfer",
    "apply_link": "https://www.admissions.illinois.edu/apply/transfer",
    "school_url": "https://www.illinois.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "April 1",
    "spring-closing-date": "October 15",
    "fall-notification-date": "By June 1",
    "spring-notification-date": "By November 15",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of Illinois at Urbana-Champaign.xlsx.pdf",
    "_source_notes": "Could not confidently parse D2 applicants/admitted/enrolled.; Official UIUC transfer dates page fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "170976",
    "name": "University of Michigan-Ann Arbor",
    "state": "MI",
    "location": "Ann Arbor",
    "type": "Public",
    "acceptance_rate_transfer": "0.3491",
    "avg_gpa_transfer": "",
    "undergrad_population": "34177",
    "tuition_in_state": "17736",
    "tuition_out_of_state": "60946",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "62",
    "residency_credits_required": "60",
    "popular_majors": "[\"Computer Science\", \"Engineering\", \"Social Sciences\", \"Biology\", \"Business\"]",
    "transfer_info_link": "https://admissions.umich.edu/apply/transfer-applicants",
    "apply_link": "https://admissions.umich.edu/apply/transfer-applicants",
    "school_url": "https://umich.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C",
    "fall-closing-date": "February 1",
    "spring-closing-date": "February 1",
    "fall-notification-date": "By 5/1",
    "spring-notification-date": "By 11/30",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of Michigan.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "199120",
    "name": "University of North Carolina at Chapel Hill",
    "state": "NC",
    "location": "Chapel Hill",
    "type": "Public",
    "acceptance_rate_transfer": "0.365",
    "avg_gpa_transfer": "",
    "undergrad_population": "20752",
    "tuition_in_state": "8994",
    "tuition_out_of_state": "41203",
    "app_fee": "85",
    "is_need_blind": "false",
    "max_credits_accepted": "75",
    "residency_credits_required": "45",
    "popular_majors": "[\"Biology\", \"Social Sciences\", \"Business\", \"Computer Science\", \"Health & Medicine\"]",
    "transfer_info_link": "https://admissions.unc.edu/apply/types-of-applications/transfer/",
    "apply_link": "https://admissions.unc.edu/apply/types-of-applications/transfer/",
    "school_url": "https://www.unc.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "15",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "February 15",
    "spring-closing-date": "",
    "fall-notification-date": "Late April",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of North Carolina at Chapel Hill.pdf",
    "_source_notes": "Could not confidently parse D2 applicants/admitted/enrolled.; Used legacy CDS.txt acceptance rate fallback.; Used legacy CDS.txt minimum credits fallback.; Used legacy CDS.txt max credits fallback.; Used legacy CDS.txt residency credits fallback.; Secondary-source UNC Chapel Hill transfer deadline estimate. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "152080",
    "name": "University of Notre Dame",
    "state": "IN",
    "location": "Notre Dame",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.2509",
    "avg_gpa_transfer": "",
    "undergrad_population": "8818",
    "tuition_in_state": "65025",
    "tuition_out_of_state": "65025",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Business\", \"Engineering\", \"Social Sciences\", \"Biology\", \"Computer Science\"]",
    "transfer_info_link": "https://admissions.nd.edu/apply/transfer-students/",
    "apply_link": "https://admissions.nd.edu/apply/transfer-students/",
    "school_url": "https://www.nd.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "3.0",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "3/15",
    "spring-closing-date": "10/1",
    "fall-notification-date": "",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of Notre Dame.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "215062",
    "name": "University of Pennsylvania",
    "state": "PA",
    "location": "Philadelphia",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0321",
    "avg_gpa_transfer": "",
    "undergrad_population": "10650",
    "tuition_in_state": "68686",
    "tuition_out_of_state": "68686",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "64",
    "residency_credits_required": "64",
    "popular_majors": "[\"Biology\", \"Social Sciences\", \"Health & Medicine\", \"Computer Science\", \"Business\"]",
    "transfer_info_link": "https://admissions.upenn.edu/admissions-and-financial-aid/apply-for-admission/transfer-admission",
    "apply_link": "https://admissions.upenn.edu/admissions-and-financial-aid/apply-for-admission/transfer-admission",
    "school_url": "https://www.upenn.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "3/15",
    "spring-closing-date": "",
    "fall-notification-date": "Early May",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of Pennsylvania.pdf",
    "_source_notes": "Used legacy CDS.txt max credits fallback.; Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "123961",
    "name": "University of Southern California",
    "state": "CA",
    "location": "Los Angeles",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.2161",
    "avg_gpa_transfer": "",
    "undergrad_population": "20443",
    "tuition_in_state": "72097",
    "tuition_out_of_state": "72097",
    "app_fee": "85",
    "is_need_blind": "false",
    "max_credits_accepted": "64",
    "residency_credits_required": "64",
    "popular_majors": "[\"Business\", \"Social Sciences\", \"Engineering\", \"Computer Science\", \"Biology\"]",
    "transfer_info_link": "https://admission.usc.edu/prospective-students/how-to-apply/transfer-students/",
    "apply_link": "https://admission.usc.edu/prospective-students/how-to-apply/transfer-students/",
    "school_url": "https://www.usc.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "2/15",
    "spring-closing-date": "",
    "fall-notification-date": "5/31",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of Southern California.pdf",
    "_source_notes": "Used legacy CDS.txt max credits fallback.; Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "228778",
    "name": "The University of Texas at Austin",
    "state": "TX",
    "location": "Austin",
    "type": "Public",
    "acceptance_rate_transfer": "0.2255",
    "avg_gpa_transfer": "",
    "undergrad_population": "42855",
    "tuition_in_state": "11688",
    "tuition_out_of_state": "44908",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "60",
    "popular_majors": "[\"Biology\", \"Engineering\", \"Business\", \"Computer Science\", \"Social Sciences\"]",
    "transfer_info_link": "https://admissions.utexas.edu/apply/transfer-students/",
    "apply_link": "https://admissions.utexas.edu/apply/transfer-students/",
    "school_url": "https://www.utexas.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "",
    "min_credits_required": "24",
    "accepts_fall": "false",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C-",
    "fall-closing-date": "3/1",
    "spring-closing-date": "9/1",
    "fall-notification-date": "Mid-Late June",
    "spring-notification-date": "December",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of Texas at Austin.pdf",
    "_source_notes": "Used legacy CDS.txt residency credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "234076",
    "name": "University of Virginia-Main Campus",
    "state": "VA",
    "location": "Charlottesville",
    "type": "Public",
    "acceptance_rate_transfer": "0.3197",
    "avg_gpa_transfer": "",
    "undergrad_population": "17597",
    "tuition_in_state": "21803",
    "tuition_out_of_state": "59512",
    "app_fee": "75",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Social Sciences\", \"Engineering\", \"Business\", \"Computer Science\", \"Biology\"]",
    "transfer_info_link": "https://admission.virginia.edu/transfer",
    "apply_link": "https://admission.virginia.edu/transfer",
    "school_url": "https://www.virginia.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "true",
    "min_gpa": "2.0",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "3/1",
    "spring-closing-date": "10/1",
    "fall-notification-date": "5/1",
    "spring-notification-date": "12/1",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of Virginia-Main Campus.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "240444",
    "name": "University of Wisconsin-Madison",
    "state": "WI",
    "location": "Madison",
    "type": "Public",
    "acceptance_rate_transfer": "0.5551",
    "avg_gpa_transfer": "",
    "undergrad_population": "36902",
    "tuition_in_state": "11603",
    "tuition_out_of_state": "42103",
    "app_fee": "70",
    "is_need_blind": "false",
    "max_credits_accepted": "72",
    "residency_credits_required": "30",
    "popular_majors": "[\"Business\", \"Biology\", \"Social Sciences\", \"Engineering\", \"Computer Science\"]",
    "transfer_info_link": "https://admissions.wisc.edu/apply-as-a-transfer-student/",
    "apply_link": "https://admissions.wisc.edu/apply-as-a-transfer-student/",
    "school_url": "https://www.wisc.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "24",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "D",
    "fall-closing-date": "3/1",
    "spring-closing-date": "10/1",
    "fall-notification-date": "3/31",
    "spring-notification-date": "12/31",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of Wisconsin-Madison.pdf",
    "_source_notes": "Could not confidently parse D2 applicants/admitted/enrolled.; Parsed AcroForm transfer totals. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "221999",
    "name": "Vanderbilt University",
    "state": "TN",
    "location": "Nashville",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.218",
    "avg_gpa_transfer": "",
    "undergrad_population": "7208",
    "tuition_in_state": "67498",
    "tuition_out_of_state": "67498",
    "app_fee": "50",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Social Sciences\", \"Engineering\", \"Computer Science\", \"Biology\", \"Psychology\"]",
    "transfer_info_link": "https://admissions.vanderbilt.edu/apply/transfer-process/",
    "apply_link": "https://admissions.vanderbilt.edu/apply/transfer-process/",
    "school_url": "https://www.vanderbilt.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "March 15",
    "spring-closing-date": "",
    "fall-notification-date": "",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Vanderbilt University.xlsx.pdf",
    "_source_notes": "Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "130794",
    "name": "Yale University",
    "state": "CT",
    "location": "New Haven",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0146",
    "avg_gpa_transfer": "",
    "undergrad_population": "6758",
    "tuition_in_state": "67250",
    "tuition_out_of_state": "67250",
    "app_fee": "80",
    "is_need_blind": "false",
    "max_credits_accepted": "72",
    "residency_credits_required": "36",
    "popular_majors": "[\"Social Sciences\", \"Biology\", \"Computer Science\", \"Engineering\", \"Psychology\"]",
    "transfer_info_link": "https://admissions.yale.edu/transfer",
    "apply_link": "https://admissions.yale.edu/transfer",
    "school_url": "https://www.yale.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "6",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "",
    "fall-closing-date": "3/1",
    "spring-closing-date": "",
    "fall-notification-date": "Mid May",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Yale University.pdf",
    "_source_notes": "Used legacy CDS.txt max credits fallback. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "164465",
    "name": "Amherst College",
    "state": "MA",
    "location": "Amherst",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0862",
    "avg_gpa_transfer": "",
    "undergrad_population": "1914",
    "tuition_in_state": "69820",
    "tuition_out_of_state": "69820",
    "app_fee": "0",
    "is_need_blind": "false",
    "max_credits_accepted": "64",
    "residency_credits_required": "64",
    "popular_majors": "[\"Social Sciences\", \"Biology\", \"Mathematics\", \"English\", \"Computer Science\"]",
    "transfer_info_link": "https://www.amherst.edu/admission/apply/transfer",
    "apply_link": "https://www.amherst.edu/admission/apply/transfer",
    "school_url": "https://www.amherst.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "32",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C",
    "fall-closing-date": "3/1",
    "spring-closing-date": "11/1",
    "fall-notification-date": "4/15",
    "spring-notification-date": "12/17",
    "_source_file": "Common_Data_Sets_2025/2024-25 Amherst College.pdf",
    "_source_notes": "Parsed CDS Section D from user-provided 2024-25 Amherst College PDF. Application fee recorded from CDS C13 when available, otherwise from the official application platform or admissions fee page."
  },
  {
    "id": "161004",
    "name": "Bowdoin College",
    "state": "ME",
    "location": "Brunswick",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0863",
    "avg_gpa_transfer": "",
    "undergrad_population": "1915",
    "tuition_in_state": "67116",
    "tuition_out_of_state": "67116",
    "app_fee": "65",
    "is_need_blind": "false",
    "max_credits_accepted": "16",
    "residency_credits_required": "16",
    "popular_majors": "[\"Social Sciences\", \"Biology\", \"Mathematics\", \"English\", \"Computer Science\"]",
    "transfer_info_link": "https://www.bowdoin.edu/admissions/apply/transfer-students.html",
    "apply_link": "https://www.bowdoin.edu/admissions/apply/transfer-students.html",
    "school_url": "https://www.bowdoin.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "3.0",
    "min_credits_required": "8",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C",
    "fall-closing-date": "3/1",
    "spring-closing-date": "",
    "fall-notification-date": "5/5",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Bowdoin College.pdf",
    "_source_notes": "Parsed Bowdoin 2024-25 CDS Section D AcroForm fields after text extraction omitted filled values. D2 reports 255 applicants, 22 admitted, 7 enrolled. D7 reports minimum college GPA 3.0; average transfer GPA is not published, so the app uses a sourced fallback estimate."
  },
  {
    "id": "126614",
    "name": "University of Colorado Boulder",
    "state": "CO",
    "location": "Boulder",
    "type": "Public",
    "acceptance_rate_transfer": "0.7198",
    "avg_gpa_transfer": "",
    "undergrad_population": "33384",
    "tuition_in_state": "12312",
    "tuition_out_of_state": "41932",
    "app_fee": "50",
    "is_need_blind": "false",
    "max_credits_accepted": "",
    "residency_credits_required": "",
    "popular_majors": "[\"Business\", \"Engineering\", \"Social Sciences\", \"Biology\", \"Computer Science\"]",
    "transfer_info_link": "https://www.colorado.edu/admissions/process/transfer",
    "apply_link": "https://www.colorado.edu/admissions/process/transfer",
    "school_url": "https://www.colorado.edu/",
    "accepts_transfer_summer": "true",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "",
    "accepts_fall": "true",
    "accepts_spring": "true",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C-",
    "fall-closing-date": "June 1",
    "spring-closing-date": "October 1",
    "fall-notification-date": "Rolling",
    "spring-notification-date": "Rolling",
    "_source_file": "Common_Data_Sets_2025/2024-25 University of Colorado Boulder.pdf",
    "_source_notes": "Parsed CDS Section D from user-provided 2024-25 University of Colorado Boulder PDF. Fall priority date is March 15; final closing date is June 1. Average transfer GPA is not published in CDS; the app uses an official program-level incoming transfer GPA fallback."
  },
  {
    "id": "168342",
    "name": "Williams College",
    "state": "MA",
    "location": "Williamstown",
    "type": "Private Non-Profit",
    "acceptance_rate_transfer": "0.0276",
    "avg_gpa_transfer": "",
    "undergrad_population": "2071",
    "tuition_in_state": "72170",
    "tuition_out_of_state": "72170",
    "app_fee": "65",
    "is_need_blind": "false",
    "max_credits_accepted": "18",
    "residency_credits_required": "18",
    "popular_majors": "[\"Social Sciences\", \"Mathematics\", \"Biology\", \"Economics\", \"English\"]",
    "transfer_info_link": "https://www.williams.edu/admission-aid/apply/transfer/",
    "apply_link": "https://www.williams.edu/admission-aid/apply/transfer/",
    "school_url": "https://www.williams.edu/",
    "accepts_transfer_summer": "false",
    "accepts_transfer_winter": "false",
    "min_gpa": "",
    "min_credits_required": "30",
    "accepts_fall": "true",
    "accepts_spring": "false",
    "in_state_min_GPA": "",
    "lowest_letter_grade_for_credit": "C-",
    "fall-closing-date": "March 2",
    "spring-closing-date": "",
    "fall-notification-date": "April 14",
    "spring-notification-date": "",
    "_source_file": "Common_Data_Sets_2025/2024-25 Williams College.pdf",
    "_source_notes": "Parsed CDS Section D from user-provided 2024-25 Williams College PDF. Credit maximum is reported as courses. Average transfer GPA is not published, so the app uses a sourced fallback estimate."
  }
];
